CREATE TABLE Person
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar NOT NULL,
    year_of_birth int     NOT NULL,
    login         varchar NOT NULL UNIQUE,
    password      varchar NOT NULL
)